### ISSUE TITLE
Investigate Low Level API Building and client.events

### ISSUE THREAD

**Issue by cbcunc** [cznethub/bimage#13]

**Comment by jnsproul** [comment]
Low level api building ruined unit tests and client.events required the use of multi-threading and didn't accomplish what was needed. The work-around implemented simply prints the docker output as it would have if it was run on the CLI. 

However, one issue is that on failure, the docker output is not printed out. I don't think currently there is a solution to this issue.

**Comment by cbcunc** [comment]
I think I will revisit this later myself. The output it most useful when there is a build failure. I add myself to the assignees.

**Comment by jnsproul** [comment]
using the events functionality doesn't provide any information, only more information on success.

However the low level api provides accurate error detail on failure.

testing.py has the low level API
testing2.py is the current method in development
here is the faulty image i provided to incite the issue.
""" Dockerfile
FROM non_existent_image:latest

RUN apt-get update \
    && apt-get install -y python3
"""

(bimage2) jnsproul@RENCI_QDNWVQP2M4 timage % python testing.py
[b'{"stream":"Step 1/2 : FROM non_existent_image:latest"}\r\n{"stream":"\\n"}\r'
 b'\n',
 b'{"errorDetail":{"message":"pull access denied for non_existent_image, reposi'
 b"tory does not exist or may require 'docker login': denied: requested access "
 b'to the resource is denied"},"error":"pull access denied for non_existent_ima'
 b"ge, repository does not exist or may require 'docker login': denied: request"
 b'ed access to the resource is denied"}\r\n']


(bimage2) jnsproul@RENCI_QDNWVQP2M4 timage % python testing2.py
Traceback (most recent call last):
  File "/Users/jnsproul/Repositories/timage/testing2.py", line 5, in <module>
    image = client.images.build(path=".", rm=True, tag='second/v1')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jnsproul/miniconda3/envs/bimage2/lib/python3.12/site-packages/docker/models/images.py", line 304, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: pull access denied for non_existent_image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by jnsproul** [comment]
Events does not add anything useful to output on build failure
