### ISSUE TITLE
Install conda-forge/google-cloud-sdk on cznworker02

### ISSUE THREAD

**Issue by cbcunc** [cznethub/bimage#14]
Will need to install the RENCI VPN. Other instructions in Slack.

**Comment by jnsproul** [comment]
$ mamba install -c conda-forge google-cloud-sdk
$ gcloud init 
// logged in as jnsproul@unc.edu
// chose bimage-project

// having trouble completing upload of docker image to google cloud, likely due to not having a RENCI VPN.

**Comment by cbcunc** [comment]
Is no one responding to your ticket re: RENCI VPN yet? RENCI VPN would have no effect in talking to Google Cloud from you laptop, however. What is the symptom/error of uploading to GC?

**Comment by jnsproul** [comment]
Fixed it by running this command 

$ gcloud auth configure-docker us-east1-docker.pkg.dev

Which adds us-east1-docker.pkg-dev to the .docker/.config.json. Will mention this in the custom exception class I'm making
