### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by cbcunc** [cznethub/bimage#21]
Well, not long after we made bimage available on anaconda.org, but not on Pypi, somebody created a Pypi package called bimage (https://pypi.org/project/bimage/). I don't think it is healthy to have package name conflicts between Anaconda and Pypi. Therefore, I think we need to rename this package (and retool every place we are using it) and register it on Pypi before registering it in Anaconda. SIgh. I'm suggesting gcimage, unless that name gets snaked first. (There's already a gimage.)

**Comment by jnsproul** [comment]
https://anaconda.org/jnsproul/clonebuildregister https://pypi.org/project/clonebuildregister/
